//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad_RA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evolucion
    {
        public int evolucion_id { get; set; }
        public int pokemon { get; set; }
        public int tipoe { get; set; }
        public int orden { get; set; }
    
        public virtual pokemon pokemon1 { get; set; }
        public virtual tipo_evolucion tipo_evolucion { get; set; }
    }
}
