//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad_RA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seguridad_apiEntities : DbContext
    {
        public seguridad_apiEntities()
            : base("name=seguridad_apiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<evolucion> evolucion { get; set; }
        public DbSet<pokemon> pokemon { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tipo> tipo { get; set; }
        public DbSet<tipo_evolucion> tipo_evolucion { get; set; }
        public DbSet<tipopkmn> tipopkmn { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<equipo> equipo { get; set; }
    }
}
