//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad_RA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokemon
    {
        public pokemon()
        {
            this.evolucion = new HashSet<evolucion>();
            this.equipo = new HashSet<equipo>();
            this.tipopkmn = new HashSet<tipopkmn>();
        }
    
        public int pokemon_id { get; set; }
        public string pokemon_nombre { get; set; }
        public string pokemon_desc { get; set; }
        public Nullable<decimal> pokemon_altura { get; set; }
        public Nullable<decimal> pokemon_peso { get; set; }
        public string pokemon_img { get; set; }
    
        public virtual ICollection<evolucion> evolucion { get; set; }
        public virtual ICollection<equipo> equipo { get; set; }
        public virtual ICollection<tipopkmn> tipopkmn { get; set; }
    }
}
