//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguridad_RA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipopkmn
    {
        public int tipopkmn_id { get; set; }
        public int tipo_id { get; set; }
        public int pokemon_id { get; set; }
    
        public virtual pokemon pokemon { get; set; }
        public virtual tipo tipo { get; set; }
    }
}
