//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class evolucion
    {
        public int evolucion_id { get; set; }
        public int pokemon { get; set; }
        public int tipoe { get; set; }
        public int orden { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual pokemon pokemon1 { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tipo_evolucion tipo_evolucion { get; set; }
    }
}
